# The folowing section is global for the app and necessary
[global-settings]
"default-profile-import-on-startup" = false                             # if true, the default profile and its playlist is loaded on startup
"default-profile-name" = "default-profile"                              # the name of the profile that is used by default

# The following commented lines are a model for defining a profile:
[default-profile]                                                       # between the brackets is the profile name to enter in the command 'profile <profile_name>'
"playlist-file-relative-path" = "playlist.txt"                          # where the plain-text playlist file shall be, it is relative to the music-list-player directory
"download-directory-relative-path" = ".cache"                           # where the audio's file shall be, it is relative to the music-list-player directory
"audio-source-selection-on-import" = false                              # if true, when the audios are imported from internet, you choose from a list which YouTube video download the audio from
"persistant-audio-cache" = true                                         # if false, when quitting the application, the audio files are deleted
"music-lyrics-search-on-import" = false                                 # if true, on importing audios, the audio's lyric are downloaded or loaded if locally available
