# The folowing section is global for the app and necessary
[global-settings]
"default-profile-import-on-startup" = false
"default-profile-name" = "example"

# The following commented lines are a model for defining a profile:
# [example_profile]
# "download-directory-relative-path" = "path/to/audio/cache/directory"  # the path is relative to the music-list-player directory
# "playlist-file-relative-path" = "path/to/playlist/file.txt"           # the path is relative to the music-list-player directory
# "persistant-audio-cache" = false
# "music-lyrics-search-on-import" = false
# "audio-source-selection-on-import" = false
