[default-profile]
"download-directory-relative-path" = "audios_cache"
"playlist-file-relative-path" = "playlists/playlist.txt"
[lofi-profile]
"download-directory-relative-path" = "audios_cache"
"playlist-file-relative-path" = "playlists/lofi_playlist.txt"