[default-profile]
"download-directory-relative-path" = "audios_cache"
"playlist-file-relative-path" = "playlists/playlist.txt"
"persistant-audio-cache" = true

[lofi-profile]
"download-directory-relative-path" = "audios_cache"
"playlist-file-relative-path" = "playlists/lofi_playlist.txt"
"persistant-audio-cache" = false
